### ISSUE TITLE
Вопрос 3. Зачем raise?

### ISSUE THREAD

**Issue by nzhukov** [python-advance/sem6-t3-Yalkinzsun#1]
https://github.com/python-advance/sem6-t3-Yalkinzsun/blob/fc70fbda88f644771c3ea323185eda75e2701434/%D0%98%D0%BD%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82%D0%BD%D0%B0%D1%8F%20%D1%81%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%201%20(%D0%BE%D0%B4%D0%B8%D0%BD%D0%BE%D1%87%D0%BA%D0%B0)/main_singleton_v2.py#L36

Я этот код уже сегодня видел у Анны. Кто автор? Вы или она?
Прокомментируйте, что делает raise? Зачем он нужен? Выполнение же упадет, когда мы будем пытаться создать еще один объект этого класса?

**Comment by Yalkinzsun** [comment]
В данном случае поднятие исключения остановит выполнение программы, если пользователь захочет создать второй экземпляр класса. Это пример не совсем рационального подхода, так как нет обработки этого исключения. Это дополнительный пример, который я сохранил для себя. В качестве ответа на задание рассматриваю файл main_singleton_v1.py

**Comment by nzhukov** [comment]
ок
